USE pronacastg;

CREATE TABLE COMPRA_PRODUCTOS_EXT (
    ITEM VARCHAR(150) NOT NULL,
    ENERO VARCHAR(30) NULL,
    FEBRERO VARCHAR(30) NULL,
    MARZO VARCHAR(30) NULL,
    ABRIL VARCHAR(30) NULL,
    MAYO VARCHAR(30) NULL,
    JUNIO VARCHAR(30) NULL,
    JULIO VARCHAR(30) NULL,
    AGOSTO VARCHAR(30) NULL,
    SEPTIEMBRE VARCHAR(30) NULL,
    OCTUBRE VARCHAR(30) NULL,
    NOVIEMBRE VARCHAR(30) NULL,
    DICIEMBRE VARCHAR(30) NULL
);

CREATE TABLE COMPRAS_CONSOLIDADAS_EXT (
    CATEGORIA VARCHAR(30) NOT NULL,
    TOTAL_USD VARCHAR(30) NOT NULL,
    TOTAL_PORCENTAJE VARCHAR(30) NOT NULL,
    PRECIO_USD VARCHAR(30) NOT NULL,
    PRECIO_PORCENTAJE VARCHAR(30) NOT NULL,
    VOLUMEN_USD VARCHAR(30) NOT NULL,
    VOLUMEN_PORCENTAJE VARCHAR(30) NOT NULL
);

CREATE TABLE INGRESOS_EXT (
    YEAR VARCHAR(30) NOT NULL,
    MONTH VARCHAR(30) NOT NULL,
    VALUE VARCHAR(30) NOT NULL
);

CREATE TABLE GASTOS_EXT (
    YEAR VARCHAR(30) NOT NULL,
    MONTH VARCHAR(30) NOT NULL,
    VALUE VARCHAR(30) NOT NULL
);

CREATE TABLE RIESGO_PROVEEDORES_EXT (
    PROVEEDOR VARCHAR(150) NOT NULL,
    YEAR VARCHAR(30) NOT NULL,
    RIESGO VARCHAR(30) NOT NULL
);